"""
擲筊模組 - 數據匯出
"""

from .divination_data import (
    DIVINATION_RESULTS,
    INTERPRETATION_TEMPLATES,
    BASIC_INFO_ERROR,
    DIVINATION_RESULT_HOLY,
    DIVINATION_RESULT_LAUGHING,
    DIVINATION_RESULT_NEGATIVE,
    THREE_CAST_INTERPRETATIONS,
)

__all__ = [
    "DIVINATION_RESULTS",
    "INTERPRETATION_TEMPLATES",
    "BASIC_INFO_ERROR",
    "DIVINATION_RESULT_HOLY",
    "DIVINATION_RESULT_LAUGHING",
    "DIVINATION_RESULT_NEGATIVE",
    "THREE_CAST_INTERPRETATIONS",
]
